config/routes.rb
Rails.application.routes.draw do
  
  resources :services
  resources :patients

  root 'patients#index'
  get 'clear_all' => 'patients#clear_all'
  

  resource :patients do
       collection do
       end
     end

end

app/models/patient.rb
class Patient < ActiveRecord::Base
    belongs_to :service, inverse_of: :patients
    after_create :defaults #this will call the 'defaults' method whenever a new entry is created
    
    def defaults
      self.update_attributes(active?: true) if active? == nil
    end
end

app/models/service.rb
class Service < ActiveRecord::Base
    has_many :patients, inverse_of: :service
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  around_filter :set_time_zone
  
  def set_time_zone
      Time.use_zone("Eastern Time (US & Canada)") { yield }
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    # @service = Service.find(:service_id)
    
    respond_to do |format|
      if @patient.save
        format.html { redirect_to patients_path, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
   
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient.service, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_path, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # DELETEALL /patients.json
  def clear_all
    Patient.where(active?: true).each do |patient|
      patient.update_attributes(active?: false) 
    end
    respond_to do |format|
      format.html { redirect_to patients_path, notice: 'All patients were successfully cleared.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:room, :initials, :estimatedate, :ptnotified, :dcsumm, :medrec, :appt, :amlabs, :ptorder, :homeo2, :tubefeeds, :walker, :otherequip, :homecare, :snfpsych, :transport, :teaching, :finassit, :conciergerx, :completedbymd, :service_id, :ptrec, :noteToStaff)
    end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  before_action :set_service, only: [:show, :edit, :update, :destroy]

  
  # GET /services
  # GET /services.json
  def index
    @services = Service.all
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to services_url, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to services_url, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :resident)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>D/C Checklist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
    <script src="bootstrap.js"></script>
</head>
<body>
<div class= "container">


<%= yield %>
</div>
</body>
</html>

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient entry from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<table>

    <div class="field">
    <%= f.label :room %><br>
    <%= f.text_field :room %>
  </div>
  
  <div class="field">
    <%= f.label :"Patient initials (FL)" %><br>
    <%= f.text_field :initials %>
  </div>
  
  <div class="field">
    <%= f.label :"Service Name" %><br>
    <%= f.select(:service_id, [['PPMC Teaching A', 1], ['PPMC Teaching B',2], ['PPMC Teaching C',3], ['PPMC Teaching D', 4], ['PPMC Hospitalist A',5], ['PPMC Hospitalist B', 6], ['PPMC Family Medicine', 7]]) %>
  </div>

  <div class="field">
    <%= f.label :"PT rec" %><br>
    <%= f.text_field :ptrec %>
  </div>
  
<br>


</table>


<div class="panel panel-default">
  <div class="panel-heading">MD tasks:</div>
  <div class="panel-body">
  


  <div class="field">
    <%= f.label :"Estimated date of discharge?" %><br>
    <p>ex: Today, Tomorrow, 2+ days, 8/1/15, day after OR date, etc</p>
    <%= f.text_area :estimatedate %>
  </div>
  
  <div class="field">
    <%= f.check_box :ptnotified %> <%= f.label :"Patient notified about noon d/c time"  %><br>
  </div>
  <div class="field">
    <%= f.check_box :dcsumm %> <%= f.label "D/c summary in progress" %><br>
    
  </div>
  <div class="field">
    <%= f.check_box :medrec %> <%= f.label :"Med rec in progress" %><br>
  </div>
  <div class="field">
    <%= f.check_box :appt %> <%= f.label :"Post-discharge appointment scheduled" %>

  </div>
  <div class="field">
    <%= f.check_box :amlabs %> <%= f.label :"Are morning labs due for medical clearance? Then I will place a one-time order @10pm" %><br>
  </div>
  <div class="field">
    <%= f.check_box :ptorder %> <%= f.label :"P/T order in" %><br>
    
  </div>
  
  </div>
  </div>

  
  <div class="panel panel-default">
  <div class="panel-heading">Patient also needs:</div>
  <div class="panel-body">
    
  <div class="field">
    <%= f.check_box :homeo2 %> <%= f.label :"Home O2"%><br>
  </div>
  <div class="field">
    <%= f.check_box :tubefeeds %> <%= f.label :"Tube feeds" %><br>
  </div>
  <div class="field">
    <%= f.check_box :walker %> <%= f.label :"Walker" %><br>
  </div>
  <div class="field">
    <%= f.check_box :otherequip %> <%= f.label :"Other Medical Equipment" %><br>
    
  </div>
  <div class="field">
    <%= f.check_box :homecare %> <%= f.label :"Home care" %><br>
  </div>
  <div class="field">
     <%= f.check_box :snfpsych %> <%= f.label :"SNF/Psych/Rehab" %><br>
  </div>
  <div class="field">
    <%= f.check_box :transport %> <%= f.label :"Transportation" %><br>
  </div>
  <div class="field">
    <%= f.check_box :teaching %> <%= f.label :"Med teaching" %><br>
  </div>
  <div class="field">
    <%= f.check_box :finassit %> <%= f.label :"Medication financial assistance" %><br>
  </div>
  <div class="field">
    <%= f.check_box :conciergerx %> <%= f.label :"Will prescriptions be filled by concierge pharmacy service?" %><br>
  </div>
  <div class="field">
     <%= f.label :"Other notes or updates for d/c staff:" %>
     <p><%= f.text_area :noteToStaff %></p>
  </div>
  </div></div>
  
  <div class="field">
    <%= f.check_box :completedbymd %> <%= f.label :"Completed by MD?" %><br>


  
  
    <div class="actions">
    <%= f.submit "Save", class:"btn btn-warning"%>
  </div>
  
  
<% end %>

app/views/patients/edit.html.erb
<h3>Editing Patient Checklist Entry</h3>

<%= render 'form' %>
<!-- probably need to make @service Service.find(@patient.service_id) -->

<!--<%= link_to 'View', @patient %> |
<%= link_to '', patients_path, class:"glyphicon glyphicon-home" %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h3 align="left"><b>Greenlight Patients</b></h3>
<p><i>-Cupp4S Staff View, All Patients-</i> &nbsp&nbsp&nbsp&nbsp&nbsp <i> <%= link_to '(MD view by service)', services_path, class: "btn btn-default" %></i></p>
<p align = "right"><i> for d/c tomorrow: <%= Date.tomorrow().to_formatted_s(:iso8601) %>  </i></p>


<table class="table table-hover" class="table table-condensed">
  <thead>
    <tr>
      <th>Room</th>
      <th>Patient (FL)</th>
      <!--<th>Est. date of d/c (per MD)</th>-->
      <th>MD done?</th>
      <th>CRC:</th>
      <th>SW:</th>
      <th>Pharm:</th>
      <th>MD:</th>
      <th>Note from MD:</th>
      <th colspan="2"></th>
      <!--<th>Leave note for d/c huddle</th>-->
    </tr>
  </thead>

  <tbody>
    <% @patients.order(:room).each do |patient| %>
      <% if patient.active? == true %>
      <tr>
        <td><%= patient.room %></td>
        <td><%= patient.initials %></td>
        <!--<td><%= patient.estimatedate %></td>-->
        <td><%= if patient.completedbymd ==true
         "Y"
        end
        %></td>
        
        
        <!--//-- CRC tasks --//-->
        <td>
        <% if patient.homeo2 == true %>
        [ ] Home O2
        <br>
        <% end %>
        <% if patient.tubefeeds == true %>
        [ ] Tube feeds
        <br>
        <% end  %>
        <% if patient.walker == true %>
        [ ] Walker
        <br>
        <% end  %>
        <% if patient.otherequip == true %>
        [ ] Other medical equipment
        <br>
        <% end  %>
        <% if patient.homecare == true %>
        [ ] Home care
        <br>
        <% end %>
        <% if patient.transport == true %>
        [ ] Transportation
        <br>
        <% end  %>
        </td>
        
        <!--//-- SW tasks --//-->
        <td>
        <% if patient.snfpsych == true %>
        [ ] SNF/Psych/Rehab
        <% end %>
        </td>

        <!--//-- Pharmacy tasks --//-->
        <td>
        <% if patient.teaching == true %>
        [ ] Med teaching
        <br>
        <% end %>
        <% if patient.finassit == true %>
        [ ] Med financial assistance
        <br>
        <% end %>
        <% if patient.conciergerx == true %>
        [ ] Rx for concierge pharmacy service
        <br>
        <% end %>
        </td>
        
        
        <!--//-- MD tasks --//-->
        <td><% if patient.completedbymd == true %>
        <% if patient.ptnotified == false %>
        [ ] Tell pt about d/c at noon
        <br>
        <% end  %>
        <% if patient.dcsumm == false %>
        [ ] D/c summary
        <br>
        <% end  %>
        <% if patient.medrec == false %>
        [ ] Update med rec
        <br>
        <% end  %>
        <% if patient.appt == false %>
        [ ] Schedule f/u appt
        <br>
        <% end  %>
        <% if patient.amlabs == false %>
        [ ] @10pm - put in AM labs for tomorrow
        <br>
        <% end  %>    
        <% if patient.ptorder == false %>
        [ ] Put in PT order
        <% end  %>
        </td>
        <% end  %>
        
        <td><%= patient.noteToStaff %></td>
        <!--<td><%= link_to 'View', patient %></td>-->
        <td><%= link_to '', edit_patient_path(patient), class:"glyphicon glyphicon-edit" %></td>
        <td><%= link_to '', patient, method: :delete, data: { confirm: 'Are you sure?' }, class:"glyphicon glyphicon-trash" %></td>
        <!--<td>
                <div class="btn-group" role="group" aria-label="...">
            <a href="/leaveNote" class="btn btn-default btn-xs" >Add</button>
            -->

        </td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<br>
<p align = "right"><%= link_to 'Clear List', 'clear_all', data: { confirm: 'Are you sure? This clears the entire list.' } %></p>
        


<br>

<%= link_to 'Add Patient Entry', new_patient_path, class:"btn btn-info" %>

<p><br></p>

 

app/views/patients/new.html.erb
<h3>New Patient</h3>

<%= render 'form' %>

<%= link_to '', patients_path,  class:"glyphicon glyphicon-home" %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Checklist items needed:</h3></h1>

<p>
  <strong>Room:</strong>
  <%= @patient.room %>
</p>

<p>
  <strong>Initials:</strong>
  <%= @patient.initials %>
</p>

<p>
  <strong>Estimated date of discharge per md:</strong>
  <%= @patient.estimatedate %>
</p>

<p>
  <%= if @patient.ptnotified==false 
  "[ ] Pt notified d/c is planned for noon"
  end
  %>
</p>

<p>
  <%= if @patient.dcsumm ==false 
  "[ ] d/c summary"
  end
  %>
</p>

<p>
  <%= if @patient.medrec==false 
  "[ ] Med rec"
  end
  %>
</p>

<p>
  <%= if @patient.appt==false
  "[ ] Schedule post d/c appt"
  end
  %>
</p>

<p>
  <%= if @patient.amlabs == true
  "[ ] Put in labs for tomorrow morning @ 10pm today"  
end
  %>
</p>

<p>
  <%= if @patient.ptorder == false 
  "[ ] PT order placement"
  end
  %>
  
</p>

<p>
  <%= if @patient.homeo2 == true 
  "[ ] Home O2"
  end
  %>
</p>

<p>
  <%= if @patient.tubefeeds == true
  "[ ] Tube feeds"
  end
  %>
</p>

<p>
  <%= if @patient.walker == true
  "[ ] Walker"
  end
  %>
</p>

<p>
  <%= if @patient.otherequip == true
  "[ ] Other medical equipment"
  end
  %>
</p>

<p>
  <%= if @patient.homecare == true
  "[ ] Home care"
  end
  %>
</p>

<p>
  <%= if @patient.snfpsych == true
  "[ ] SNF/psych/rehab needed (alcohol/drugs)"
  end
  %>
</p>

<p>
  <%= if @patient.transport == true
  "[ ] Transportation"
  end
  %>
</p>

<p>
  <%= if @patient.teaching == true
  "[ ] Medication teaching"
  end
  %>
</p>

<p>
  <%= if @patient.finassit == true
  "[ ] Medication financial assistance"
  end
  %>
</p>

<p>
  <%= if @patient.conciergerx == true
  "[ ] Concierge pharmacy"
  end
  %>
</p>

<p>
  <%= if @patient.completedbymd == true
  "checklist completed by MD at: " + "#{ @patient.updated_at.to_formatted_s(:short) }"
  end
  %>
</p>

<button type="button" class="btn btn-default">
  <a href = "<%= edit_patient_path(@patient) %>", class="glyphicon glyphicon-edit"></a>
</button>
<button type="button" class="btn btn-success">
  <a href= "<%= patients_path %>", class="glyphicon glyphicon-home"></a>
</button>
<%= link_to 'Add Another Patient', new_patient_path, class: "btn btn-info" %>

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<table>
    <tr>
    <div class="field">
    <%= f.label "Service Name" %><br>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :"Resident Name" %><br>
    <%= f.text_field :resident %>
  </div>
  

  </tr>
</table>



  <div class="actions">
    <%= f.submit "Submit", class:"btn btn-warning"%>
  </div>
  
  
  
  
  
<% end %>

app/views/services/_formnewservice.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :resident %><br>
    <%= f.text_field :resident %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/services/edit.html.erb
<h3>Editing Patient Checklist Entry</h3>

<%= render 'form' %>

<!--<%= link_to 'View', @patient %> |-->
<%= link_to '', services_path, class:"glyphicon glyphicon-home" %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h3 align="left"><b>Greenlight Patients</b> </h3>
<p><i>-MD View, All Services-</i></p>
<p align = "right"><i> for d/c tomorrow: <%= Date.tomorrow().to_formatted_s(:iso8601) %>  </i></p>

<table class="table table-hover" class="table table-condensed">
  <thead>
    <tr>
      <th>Service Name</th>
      <th>Resident</th>
      <th colspan="1">Patient Checklists</th>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.name %></td>
        <td><%= service.resident %></td>
        <td><%= link_to " #{ (Patient.where(service_id: service.id, active?:true)).count } Patients", service %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/services/new.html.erb
<h3>New Service</h3>

<%= render 'form' %>

<%= link_to '', services_path,  class:"glyphicon glyphicon-home" %>

app/views/services/newservicecreation.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<!-- akin to the "index" view for patients -->
<p id="notice"><%= notice %></p>

<h3 align="left"><b>Discharge Checklists</b> </h3>
<p><i>-MD View, <%= @service.name %>-</i></p>
<p align = "right"><i> for d/c tomorrow: <%= Date.tomorrow().to_formatted_s(:iso8601) %>  </i></p>

<table class="table table-hover" class="table table-condensed">
  <thead>
    <tr>
      <th>New</th>
      <th></th>
      <th>Room</th>
      <th>Patient (FL)</th>
      <!--<th>Est. d/c date</th>-->
      <!--<th>SW tasks</th>-->
      <!--<th>PT tasks</th>-->
      <!--<th>Pharmacy tasks</th>-->
      <th>MD to-do:</th>
      <th>PT rec:</th>
      <th colspan="1"></th>
      <!--<th>Leave note for d/c huddle</th>-->
    </tr>
  </thead>

  <tbody>
    <% @service.patients.order(:room).each do |patient| %>
      <% if patient.active? == true %>
      <tr>
        <td><%= "*" unless patient.completedbymd == true %></td>
        <td><%= link_to '', edit_patient_path(patient), class:"glyphicon glyphicon-edit" %></td>
        
        <td><%= patient.room %></td>
        <td><%= patient.initials %></td>
        <!--<td><%= patient.estimatedate %></td>-->
        <td><% if patient.completedbymd == true %>

        <% if patient.ptnotified == false %>
        [ ] Tell pt about d/c at noon
        <br>
        <% end  %>
        <% if patient.dcsumm == false %>
        [ ] D/c summary
        <br>
        <% end  %>
        <% if patient.medrec == false %>
        [ ] Update med rec
        <br>
        <% end  %>

        <% if patient.appt == false %>
        [ ] Schedule f/u appt
        <br>
        <% end  %>
        <% if patient.amlabs == false %>
        [ ] @10pm - put in AM labs for tomorrow
        <br>
        <% end  %>    
        <% if patient.ptorder == false %>
        [ ] Put in PT order
        <br>
        <% end  %>
        <% end %>
        </td>
        
        <td><%= patient.ptrec %></td>
        
        
        
        <td><%= link_to '', patient, method: :delete, data: { confirm: 'Are you sure?' }, class:"glyphicon glyphicon-trash" %></td>
        
        <!--<td>
                <div class="btn-group" role="group" aria-label="...">
            <a href="/leaveNote" class="btn btn-default btn-xs" >Add</button>
            </td>-->

      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>


<!--<%= link_to '', services_path,  class:"glyphicon glyphicon-home" %>-->